name: "Feature"
title: "Feat# "
description: "새로운 기능 추가"
labels: ["enhancement"]
body:
  - type: textarea
    id: feature_description
    attributes:
      label: 작업할 내용
      description: 새로운 기능에 대한 설명을 작성해 주세요.
      placeholder: 자세히 적을수록 좋습니다!
    validations:
      required: true
  - type: textarea
    id: reviewer_description
    attributes:
      label: 알야아 할 것
      description: 리뷰어들이 알아야할 것이 있다면 작성해 주세요.